djangomedicalproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('egungunbecareful/', admin.site.urls),
    path('', include('pages.urls')),
]

pages/urls.py
from django.urls import path

from pages.views.general import StatPageView, HomePageView
from pages.views.patients import show_login, show_signup, show_logout, patient_create_view
from pages.views.practitioner import login_page, logout_page, signup_page, show_doc_info

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home_page'),
    path('stat/', StatPageView.as_view(), name='stat_page'),
    path('report/', patient_create_view, name='patient_home'),
    path('dashboard/', show_doc_info, name='practitioner_home'),
    path('accounts/login/', show_login, name='patient_login'),
    path('accounts/signup/', show_signup, name='patient_signup'),
    path('accounts/logout/', show_logout, name='patient_logout'),
    path('accounts/p/login/', login_page, name='practitioner_login'),
    path('accounts/p/signup/', signup_page, name='practitioner_signup'),
    path('accounts/p/logout/', logout_page, name='practitioner_logout'),
]

templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>MedInfo App</title>
    <meta name="description"
          content=""/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="Codeply">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static "pages/css/animate.min.css" %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link rel="stylesheet" href="{% static "pages/css/styles.css" %}">
</head>
<body>
<nav id="topNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand page-scroll" href="{% url 'pages:home_page' %}"><i
                    class="ion-ios-analytics-outline"></i> MedInfo App</a>
        </div>
        <div class="navbar-collapse collapse" id="bs-navbar">
            <ul class="nav navbar-nav">
                {% block authenticate %}
                    {% if user.is_authenticated %}
                        <li>
                            <a class="page-scroll">Hi, {{ user.first_name }}</a>
                        </li>

                        <li>
                            <a class="page-scroll" href="{% url 'pages:patient_logout' %}">Logout</a>
                        </li>
                    {% endif %}
                {% endblock %}

                {% if not user.is_authenticated %}
                    <li>
                        <a class="page-scroll" href="{% url 'pages:practitioner_login' %}">Practitioner Login</a>
                    </li>

                    <li>
                        <a class="page-scroll" href="{% url 'pages:patient_login' %}">Patient Login</a>
                    </li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="page-scroll" data-toggle="modal"
                       href="https://github.com/Toluwalemi/django-medical-app">About</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block header %}
{% endblock %}

{% block section %}
{% endblock %}

{% block login %}
{% endblock %}

<!--scripts loaded here -->
<script src="{% static 'pages/js/jquery.min.js' %}"></script>
<script src="{% static 'pages/js/bootstrap.min.js' %}"></script>
<script src="{% static 'pages/js/jquery.easing.min.js' %}"></script>
<script src="{% static 'pages/js/wow.js' %}"></script>
<script src="{% static 'pages/js/scripts.js' %}"></script>
</body>
</html>