djangomedicalproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('egungunbecareful/', admin.site.urls),
    path('', include('pages.urls')),
]

pages/urls.py
from django.urls import path

from pages.views.general import StatPageView, HomePageView
from pages.views.patients import show_login, show_signup, show_logout, patient_create_view
from pages.views.practitioner import login_page, logout_page, signup_page, show_doc_info

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home_page'),
    path('stat/', StatPageView.as_view(), name='stat_page'),
    path('report/', patient_create_view, name='patient_home'),
    path('dashboard/', show_doc_info, name='practitioner_home'),
    path('accounts/login/', show_login, name='patient_login'),
    path('accounts/signup/', show_signup, name='patient_signup'),
    path('accounts/logout/', show_logout, name='patient_logout'),
    path('accounts/p/login/', login_page, name='practitioner_login'),
    path('accounts/p/signup/', signup_page, name='practitioner_signup'),
    path('accounts/p/logout/', logout_page, name='practitioner_logout'),
]

templates/pages/dashboard.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Filter Form</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'pages/css/dashboard.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link">Hi, {{ user.get_full_name }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:practitioner_logout' %}">Signout</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<main role="main" class="container">

    <h3>Filter Medical Records</h3>
    <form method="GET" action=".">
        <div class="form-row">
            <div class="form-group col-12">
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" type="search" name="summary_contains"
                           placeholder="Summary contains..."/>
                    <span class="input-group-append">
                        <div class="input-group-text bg-transparent">
                            <i class="fa fa-search"></i>
                        </div>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-12">
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" type="search" name="blood_type"
                           placeholder="Exact Blood Type..."/>
                    <span class="input-group-append">
                        <div class="input-group-text bg-transparent">
                            <i class="fa fa-search"></i>
                        </div>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-12">
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" type="search" name="exact_gender"
                           placeholder="Exact Gender"/>
                    <span class="input-group-append">
                        <div class="input-group-text bg-transparent">
                            <i class="fa fa-search"></i>
                        </div>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-2 col-lg-2">
                <label for="viewCountMin">Minimum Age</label>
                <input type="number" min=0 class="form-control" id="viewCountMin" placeholder="0" name="age_min">
            </div>
            <div class="form-group col-md-2 col-lg-2">
                <label for="viewCountMax">Maximum Age</label>
                <input type="number" min=0 class="form-control" id="viewCountMax" placeholder="100?"
                       name="age_max">
            </div>

            <div class="form-group col-md-4">
                <label for="illness">Illness</label>
                <select id="illness" class="form-control" name="illness">
                    <option selected>Choose...</option>
                    {% for ill in illnesses %}
                        <option value="{{ ill }}">{{ ill }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Search</button>
    </form>

    <hr/>
    <table class="table">
        <thead>
        <tr>
            <th>Summary</th>
            <th>E-Mail</th>
            <th>Illness</th>
            <th>Gender</th>
            <th>Blood Group</th>
            <th>Age</th>
            <th>Creation Date</th>
        </tr>
        </thead>
        <tbody>
        {% for info in queryset %}
            <tr>
                <td>{{ info.summary }}</td>

                <td>{{ info.patient.user }}</td>

                {% for ill in info.illnesses.all %}
                    <td>{{ ill }}</td>
                {% endfor %}

                <td>{{ info.gender }}</td>
                <td>{{ info.blood_group }}</td>
                <td>{{ info.age }}</td>
                <td>{{ info.created }}</td>

            </tr>
        {% endfor %}
        </tbody>
    </table>

</main>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>

</html>

templates/pages/landing_page.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block header %}
    <header id="first">
        <div class="header-content">
            <div class="inner">
                <h1 class="cursive">Welcome to MedInfo App</h1>
                <h4>Kindly SignUp as a Patient or Medical Practitioner</h4>
                <hr>
                <a href="{% url 'pages:patient_signup' %}" class="btn btn-primary btn-xl">I'm a
                    Patient</a> &nbsp; <a href="{% url 'pages:practitioner_signup' %}"
                                          class="btn btn-primary btn-xl page-scroll">I'm a Practitioner</a>
            </div>
        </div>
    </header>
{% endblock %}

templates/pages/report.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Filter Form</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'pages/css/dashboard.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Hi ()</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pages:patient_logout' %}">Signout</a>
            </li>
        </ul>
    </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <h1>Medical Information</h1>
            <form class="form-horizontal" action="" method="post">
                {% csrf_token %}
                <fieldset>

                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label">Summary</label>
                        <div class="col-md-4">
                            <input name="summary" type="text" class="form-control input-md">

                        </div>
                    </div>

                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label">Gender</label>
                        <div class="col-md-4">
                            <input name="gender" type="text" class="form-control input-md">

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Blood Group</label>
                        <div class="col-md-4">
                            <input name="blood_group" type="text" class="form-control input-md">

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Age</label>
                        <div class="col-md-4">
                            <input name="age" type="text" class="form-control input-md">

                        </div>
                    </div>

                    <div class="form-group col-md-4">
                        <label for="illness">Illness</label>
                        <select id="illness" class="form-control" name="illness">
                            <option selected>Choose...</option>
                            {% for ill in illnesses %}
                                <option value="{{ ill }}">{{ ill }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </fieldset>
            </form>
        </div>
    </div>
</div>

</main>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>

</html>

{#<div class="col-md-12">#}
{#    <label></label>#}
{#    <textarea class="form-control" rows="9" placeholder="Your message here.."></textarea>#}
{#</div>#}

templates/pages/stat.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Statistics</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'pages/css/dashboard.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link">Hi, {{ user.get_full_name }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:practitioner_logout' %}">Signout</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<main role="main" class="container">

    <h3>Statistics</h3>
    <hr/>
    <table class="table">
        <thead>
        <tr>
            <th>Number of Patients</th>
            <th>Patients with Ebola</th>
            <th>Patients with Lassa Fever</th>
            <th>Patients with Malaria</th>
            <th>Patients with Covid-19</th>
            <th>Patients with Typhoid</th>
        </tr>
        </thead>
        <tbody>
{#        {% for info in queryset %}#}
{#            <tr>#}
{#                <td>{{ info.summary }}</td>#}
{##}
{#                <td>{{ info.patient.user }}</td>#}
{##}
{#                {% for ill in info.illnesses.all %}#}
{#                    <td>{{ ill }}</td>#}
{#                {% endfor %}#}
{##}
{#                <td>{{ info.gender }}</td>#}
{#                <td>{{ info.age }}</td>#}
{#                <td>{{ info.blood_group }}</td>#}
{#                <td>{{ info.created }}</td>#}
{##}
{#            </tr>#}
{#        {% endfor %}#}
        </tbody>
    </table>

</main>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>

</html>